"""Initial migration.

Revision ID: 792317950192
Revises: 1fbb2572fcaa
Create Date: 2024-06-12 12:36:52.118014

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '792317950192'
down_revision = '1fbb2572fcaa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('earthquakes', 'id',
               existing_type=sa.VARCHAR(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('earthquakes', 'magnitude',
               existing_type=sa.FLOAT(),
               nullable=False)
    op.alter_column('earthquakes', 'location',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('earthquakes', 'year',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('earthquakes', 'year',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('earthquakes', 'location',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('earthquakes', 'magnitude',
               existing_type=sa.FLOAT(),
               nullable=True)
    op.alter_column('earthquakes', 'id',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(),
               existing_nullable=False,
               autoincrement=True)
    # ### end Alembic commands ###
